[project]
name = "bssig"
version = "0.1.0"
description = "Blender Synthetic Space Imagery Generator"
authors = ["Noah Grattan <23grattan@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.4,<3.13"
numpy = ">=2.0.1,<2.1"
scikit-image = ">=0.24.0,<0.25"

[pypi-dependencies]
fake-bpy-module = ">=4.2"
scipy = ">=1.14.0"
