[project]
name = "bssig"
version = "0.1.0"
description = "Blender Synthetic Space Imagery Generator"
authors = ["ngrattan <23grattan@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.4,<3.13"

[pypi-dependencies]
fake-bpy-module = ">=4.2"
